### ISSUE TITLE
Properly rebuild just container when container hash changes

### ISSUE THREAD

**Issue by omstrumpf** [envy-project/envy#27]
Currently we're always rebuilding the entire ENVy environment, even when just the setup-steps section changes. We're already tracking that hash separately from the base image and native dependencies, so we have the requisite information available to not destroy the ENVy image.

This saves us the cost of re-installing native dependencies every time we change build steps.

Currently, our build steps won't know that they need to trigger on a fresh container. We can probably just pass a `fresh_container` or `ignore_triggers` flag to the setup step builder to solve this.

**Comment by Tim-Willard** [comment]
This issue was fixed as a part of #42
